### ISSUE TITLE
Browser Refresh (F5, etc.) on CodeReader and Profile pages causes 404 error

### ISSUE THREAD

**Issue by snookerc** [benjaminsampica/cAIsy#1]
Pressing F5 on ANY of the pages except for "Home" (Code Converter) throws a 404 error, and the "Back" button doesn't help.  

https://benjaminsampica.github.io/cAIsy/CodeReader
https://benjaminsampica.github.io/cAIsy/Profile
https://benjaminsampica.github.io/cAIsy/ChatHistory

Have to manually re-navigate to https://benjaminsampica.github.io/cAIsy/ to get it to work again.

**Comment by benjaminsampica** [comment]
Need to configure this with a custom 404 page that redirects to our index.html page.

More info:

https://github.com/dotnet/aspnetcore/issues/20788#issuecomment-613014784

**Comment by benjaminsampica** [comment]
How to w/ JavaScript:

https://blog.elmah.io/blazor-wasm-404-error-and-fix-for-github-pages/amp/

alternative:

https://devkimchi.com/2022/10/05/404-page-of-blazor-wasm-on-gh-pages/
